//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

@import Foundation;

#import <IDESourceEditor/IDESourceCodeDocument.h>
#import <IDELanguageSupportUI/IDEToyboxDocumentLocationDelegate-Protocol.h>

@class DVTFilePath, DVTMapTable, DVTSDK, IDEToybox;

@interface IDEPlaygroundDocument : IDESourceCodeDocument <IDEToyboxDocumentLocationDelegate>

@property(readonly, copy) NSUUID *currentUUID; // @synthesize currentUUID=_currentUUID;
@property(nonatomic) BOOL runsInFullSimulator; // @synthesize runsInFullSimulator=_runsInFullSimulator;
@property(retain, nonatomic) DVTFilePath *frameworkSearchPath; // @synthesize frameworkSearchPath=_frameworkSearchPath;
@property(copy, nonatomic) NSURL *originalContentURLDuringSaving; // @synthesize originalContentURLDuringSaving=_originalContentURLDuringSaving;
@property(retain) NSError *nonFatalReadError; // @synthesize nonFatalReadError=_nonFatalReadError;
@property NSUInteger autoTerminationDelay; // @synthesize autoTerminationDelay=_autoTerminationDelay;
@property(nonatomic) BOOL allowsReset; // @synthesize allowsReset=_allowsReset;
@property BOOL lastExpressionDidComplete; // @synthesize lastExpressionDidComplete=_lastExpressionDidComplete;
@property BOOL playgroundExpressionIsComplete; // @synthesize playgroundExpressionIsComplete=_playgroundExpressionIsComplete;
@property BOOL isReplayingSerializedResults; // @synthesize isReplayingSerializedResults=_isReplayingSerializedResults;
@property BOOL executionIsInProgress; // @synthesize executionIsInProgress=_executionIsInProgress;
@property(readonly) IDEToybox *toybox; // @synthesize toybox=_toybox;
@property(copy, nonatomic) NSArray *executionIssues; // @synthesize executionIssues=_executionIssues;
@property(copy, nonatomic) NSArray *sourceCodePlaygroundSectionCharacterRanges; // @synthesize sourceCodePlaygroundSectionCharacterRanges=_sourceCodePlaygroundSectionCharacterRanges;
@property(copy, nonatomic) NSArray *playgroundSections; // @synthesize playgroundSections=_playgroundSections;
@property(copy, nonatomic) NSString *sdkIdentifier; // @synthesize sdkIdentifier=_sdkIdentifier;
- (id)willPresentError:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)textStorageDidProcessEditing:(id)arg1;
- (void)sourceLanguageServiceAvailabilityNotification:(BOOL)arg1 message:(id)arg2;
- (struct _NSRange)characterRangeFromDocumentLocation:(id)arg1;
- (id)indexCompatibleLocationFromLocation:(id)arg1;
- (id)editorCompatibleLocationFromLocation:(id)arg1;
- (void)editorDocumentWillClose;
- (id)playgroundSectionsFromXMLElement:(id)arg1 enclosingFileWrapper:(id)arg2 error:(id *)arg3;
- (id)xmlElementConstructingFileWrapper:(id)arg1;
- (id)dataOfType:(id)arg1 contructingFileWrapper:(id)arg2 error:(id *)arg3;
- (id)fileWrapperOfType:(id)arg1 error:(id *)arg2;
- (id)contentPathsToPreserveOnSave;
- (BOOL)writeToURL:(id)arg1 ofType:(id)arg2 forSaveOperation:(NSUInteger)arg3 originalContentsURL:(id)arg4 error:(id *)arg5;
- (BOOL)readContentFromData:(id)arg1 ofType:(id)arg2 enclosingFileWrapper:(id)arg3 error:(id *)arg4;
- (BOOL)readFromFileWrapper:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (id)updatedLocationFromLocation:(id)arg1 toTimestamp:(double)arg2;
- (void)_clearSerializedPlaygroundResultsIfNeeded;
- (BOOL)_shouldSavePlaygroundResultsToWrapperAndQuit;
- (BOOL)_shouldSavePlaygroundResultsToWrapper;
- (id)sourceLanguageServiceContext;
@property(readonly) NSDictionary *buildSettings;
- (id)targetTriple;
- (void)cancelExecutionInWorkspace:(id)arg1;
- (BOOL)executeInWorkspace:(id)arg1 fromEditor:(id)arg2 replayFromSerializedData:(BOOL)arg3 error:(id *)arg4 completionBlock:(void(^)(void))arg5;
- (BOOL)_shouldHandlePlaygroundEventFromGeneration:(NSUInteger)arg1;
- (void)unregisterEditor:(id)arg1;
- (void)registerEditor:(id)arg1;
- (id)_preparationParametersForWorkspace:(id)arg1 outAppBundle:(id *)arg2 error:(id *)arg3;
- (id)regeneratePlaygroundAppBundleForDevice:(id)arg1 error:(id *)arg2;
- (id)sourceCodeForExecution;
- (void)executionGenerationDidEnd;
- (void)playgroundExpressionCompleted;
- (void)executionGenerationWillEnd;
- (void)beginExecutionGenerationIsReplayingSerializedResults:(BOOL)arg1;
- (void)addPlaygroundLoggerResult:(id)arg1;
- (void)removeAllPlaygroundResults;
@property(readonly) DVTFilePath *resourcesDirectoryPath;
- (void)resetPlayground;
@property(readonly, copy, nonatomic) NSArray *sourceCodePlaygroundSections;
- (id)contentsURL;
@property(readonly) DVTSDK *sdk;
- (BOOL)showRunInFullSimulatorChoice;
@property(nonatomic) NSUInteger platform;

@end

