//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

@import Foundation;

@class DVTSourceLandmarkItem, DVTTextDocumentLocation;

@protocol DVTSourceLandmarkProvider <NSObject>
- (DVTTextDocumentLocation *)documentLocationFromCharacterRange:(NSRange)arg1;
- (NSRange)characterRangeFromDocumentLocation:(DVTTextDocumentLocation *)arg1;
- (NSRange)lineRangeOfSourceLandmark:(DVTSourceLandmarkItem *)arg1;
- (DVTSourceLandmarkItem *)sourceLandmarkItemAtLineNumber:(NSUInteger)arg1;
- (DVTSourceLandmarkItem *)sourceLandmarkItemAtCharacterIndex:(NSUInteger)arg1;
@end

