//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

@import Foundation;

@class DVTTextDocumentLocation, DVTTextStorage, IDEDiagnosticController, NSURL;

@protocol IDEDiagnosticControllerDataSource <NSObject>
@property(readonly) IDEDiagnosticController *diagnosticController;
@property(readonly) DVTTextStorage *textStorage;
@property(readonly) NSURL *fileURL;
- (DVTTextDocumentLocation *)documentLocationFromCharacterRange:(NSRange)arg1;
@end

