//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

@import Foundation;

#import <IDEKit/IDEEditorDocument.h>

#import <IDESourceEditor/DVTSourceLandmarkProvider-Protocol.h>
#import <IDESourceEditor/DVTSourceTextViewDelegate-Protocol.h>
#import <IDESourceEditor/DVTTextFindable-Protocol.h>
#import <IDESourceEditor/DVTTextReplacable-Protocol.h>
#import <IDESourceEditor/DVTTextStorageDelegate-Protocol.h>
#import <IDESourceEditor/IDEDiagnosticControllerDataSource-Protocol.h>
#import <IDESourceEditor/IDEDocumentStructureProviding-Protocol.h>
#import <IDESourceEditor/IDEObjectiveCSourceCodeGenerationDestination-Protocol.h>

@class DVTDelayedInvocation, DVTFileDataType, DVTGeneratedContentProvider, DVTNotificationToken, DVTObservingToken, DVTPerformanceMetric, DVTSourceCodeLanguage, DVTTextStorage, IDEDiagnosticController, IDEGeneratedContentStatusContext, IDESourceCodeAdjustNodeTypesRequest, NSArray, NSDictionary, NSMutableArray, NSMutableSet, NSSet, NSString, NSURL;

@interface IDESourceCodeDocument : IDEEditorDocument <IDEDiagnosticControllerDataSource, IDEDocumentStructureProviding, DVTTextFindable, DVTTextReplacable, DVTTextStorageDelegate, IDEObjectiveCSourceCodeGenerationDestination, DVTSourceLandmarkProvider, DVTSourceTextViewDelegate>

+ (id)syntaxColoringPrefetchLogAspect;
+ (id)topLevelStructureLogAspect;
@property(copy) NSDictionary *_firstEditorWorkspaceBuildSettings; // @synthesize _firstEditorWorkspaceBuildSettings=__firstEditorWorkspaceBuildSettings;
@property(copy) NSSet *_firstEditorWorkspacePreferredIndexableIdentifiers; // @synthesize _firstEditorWorkspacePreferredIndexableIdentifiers=__firstEditorWorkspacePreferredIndexableIdentifiers;
@property BOOL notifiesWhenClosing; // @synthesize notifiesWhenClosing=_notifiesWhenClosing;
@property(retain) IDEGeneratedContentStatusContext *generatedContentStatusContext; // @synthesize generatedContentStatusContext=_generatedContentStatusContext;
@property BOOL generatesContent; // @synthesize generatesContent=_generatesContent;
@property(readonly) NSRange prefetchedNodeTypesLineRange; // @synthesize prefetchedNodeTypesLineRange=_prefetchedNodeTypesLineRange;
@property(nonatomic) NSUInteger lineEndings; // @synthesize lineEndings=_lineEndings;
@property NSUInteger textEncoding; // @synthesize textEncoding=_textEncoding;
@property(nonatomic) BOOL usesLanguageFromFileDataType; // @synthesize usesLanguageFromFileDataType=_usesLanguageFromFileDataType;
@property(retain, nonatomic) DVTSourceCodeLanguage *language; // @synthesize language=_language;
@property(readonly) DVTTextStorage *textStorage; // @synthesize textStorage=_textStorage;
- (void)_delayedDropRecomputableState:(id)arg1;
- (void)_restoreRecomputableState;
- (void)_dropRecomputableState;
- (void)_documentMovingToForeground;
- (void)_documentMovingToBackground:(BOOL)arg1;
- (void)registerDocumentEditor:(id)arg1;
- (void)unregisterDocumentEditor:(id)arg1;
- (id)_firstEditorWorkspace;
- (id)_firstEditor;
- (id)sourceCodeGenerator:(id)arg1 commitInsertionOfSourceCodeForCompositeResult:(id)arg2 error:(id *)arg3;
- (id)sourceCodeGenerator:(id)arg1 prepareToAddObjectiveCAtSynthesizeWithName:(id)arg2 inClassNamed:(id)arg3 options:(id)arg4 error:(id *)arg5;
- (id)sourceCodeGenerator:(id)arg1 prepareToAddObjectiveCPropertyDeclarationWithName:(id)arg2 type:(id)arg3 inClassNamed:(id)arg4 options:(id)arg5 error:(id *)arg6;
- (id)sourceCodeGenerator:(id)arg1 prepareToAddObjectiveCPropertyReleaseForTeardownWithName:(id)arg2 type:(id)arg3 inClassNamed:(id)arg4 options:(id)arg5 error:(id *)arg6;
- (id)sourceCodeGenerator:(id)arg1 prepareToAddObjectiveCInstanceVariableReleaseForTeardownWithName:(id)arg2 inClassNamed:(id)arg3 options:(id)arg4 error:(id *)arg5;
- (id)_primitiveAddObjectiveCReleaseForTeardownMethodWithSourceCodeGenerator:(id)arg1 withReleaseCallCode:(id)arg2 inClassNamed:(id)arg3 options:(id)arg4 error:(id *)arg5;
- (id)sourceCodeGenerator:(id)arg1 prepareToAddObjectiveCInstanceVariableDeclarationWithName:(id)arg2 type:(id)arg3 inClassNamed:(id)arg4 options:(id)arg5 error:(id *)arg6;
- (id)sourceCodeGenerator:(id)arg1 prepareToAddObjectiveCClassMethodDefinitionWithName:(id)arg2 inClassNamed:(id)arg3 options:(id)arg4 error:(id *)arg5;
- (id)sourceCodeGenerator:(id)arg1 prepareToAddObjectiveCClassMethodDeclarationWithName:(id)arg2 inClassNamed:(id)arg3 options:(id)arg4 error:(id *)arg5;
- (id)sourceCodeGenerator:(id)arg1 prepareToAddObjectiveCInstanceMethodDefinitionWithName:(id)arg2 inClassNamed:(id)arg3 options:(id)arg4 error:(id *)arg5;
- (id)_primitiveAppendObjectiveCSourceCode:(id)arg1 afterItem:(id)arg2 prependNewLine:(BOOL)arg3;
- (id)sourceCodeGenerator:(id)arg1 prepareToAddObjectiveCInstanceMethodDeclarationWithName:(id)arg2 inClassNamed:(id)arg3 options:(id)arg4 error:(id *)arg5;
- (id)_primitiveAddObjectiveCMethodSourceCode:(id)arg1 toClassItem:(id)arg2 withOptions:(id)arg3 error:(id *)arg4;
- (id)_primitiveAddObjectiveCSourceCode:(id)arg1 toClassItem:(id)arg2 withOptions:(id)arg3 insertAdditionalNewlineWhenInsertingWithAfterBeforeHint:(BOOL)arg4 insertAtEndWhenInsertingWithoutHint:(BOOL)arg5 insertAfterObjCBlockWhenInsertingAtBeginning:(BOOL)arg6 ignoreHintItemsConformingToSpecifications:(id)arg7 onlyConsiderItemsConformingToSpecifications:(id)arg8 error:(id *)arg9;
- (id)_insertObjectiveCSourceCode:(id)arg1 inTeardownMethodForClassNamed:(id)arg2 options:(id)arg3 error:(id *)arg4;
- (id)_teardownMethodNameForSourceCodeGeneratorWithOptions:(id)arg1;
- (BOOL)_hasObjCMethodImplementationForName:(id)arg1 forClassNamed:(id)arg2;
- (id)_objCMethodImplementationItemForName:(id)arg1 inClassItem:(id)arg2;
- (id)_insertObjCSourceCode:(id)arg1 inTopLevelOfClassItem:(id)arg2 withInsertAfterHint:(id)arg3 andInsertBeforeHint:(id)arg4 ignoreHintItemsConformingToSpecifications:(id)arg5 onlyConsiderItemsConformingToSpecifications:(id)arg6 insertAdditionalNewline:(BOOL)arg7 insertAtEndWhenInsertingWithoutHint:(BOOL)arg8 insertAfterObjCBlockWhenInsertingAtBeginning:(BOOL)arg9;
- (id)_insertObjCSourceCode:(id)arg1 inContainingSourceModelItem:(id)arg2 withInsertAfterHint:(id)arg3 andInsertBeforeHint:(id)arg4 ignoreHintItemsConformingToSpecifications:(id)arg5 onlyConsiderItemsConformingToSpecifications:(id)arg6 insertAdditionalNewline:(BOOL)arg7 fallbackInsertionBlock:(void(^)(void))arg8;
- (long long)_insertionHintMatchPriorityForObjCSourceModelItem:(id)arg1 givenInsertionHintItemName:(id)arg2 andLanguageSpecification:(id)arg3 ignoreItemsConformingToSpecifications:(id)arg4 onlyConsiderItemsConformingToSpecifications:(id)arg5;
- (id)_insertObjCSourceCode:(id)arg1 inTopLevelOfClassItem:(id)arg2 asCloseAsPossibleToLineNumber:(NSUInteger)arg3 error:(id *)arg4;
- (id)_insertObjCSourceCode:(id)arg1 inContainingSourceModelItem:(id)arg2 asCloseAsPossibleToLineNumber:(NSUInteger)arg3 firstPossibleItemToInsertBefore:(id)arg4 error:(id *)arg5;
- (id)_insertionHintForObjCSourceModelItem:(id)arg1;
- (id)_firstObjCSourceModelItemToInsertBeforeInInstanceVariableBlock:(id)arg1;
- (id)_firstTopLevelObjCInterfaceSourceModelItemToInsertBeforeInClassItem:(id)arg1;
- (id)_insertSourceCode:(id)arg1 atBeginningOfClassSourceModelItem:(id)arg2 insertOnNextLine:(BOOL)arg3 insertAfterObjCBlock:(BOOL)arg4;
- (id)_insertSourceCode:(id)arg1 atEndOfClassSourceModelItem:(id)arg2 insertOnNextLine:(BOOL)arg3;
- (id)_insertSourceCode:(id)arg1 atEndOfContainingSourceModelItem:(id)arg2 insertOnNextLine:(BOOL)arg3 beforeItemMatchingPredicateBlock:(void(^)(void))arg4;
- (id)_insertSourceCode:(id)arg1 atBeginningOfContainingSourceModelItem:(id)arg2 insertOnNextLine:(BOOL)arg3 afterItemMatchingPredicateBlock:(void(^)(void))arg4;
- (id)_primitiveInsertSourceCode:(id)arg1 atBeginning:(BOOL)arg2 ofContainingSourceModelItem:(id)arg3 insertOnNextLine:(BOOL)arg4 afterOrBeforeItemMatchingPredicateBlock:(void(^)(void))arg5;
- (id)textDocumentLocationForInsertingSourceCode:(id)arg1 atLocation:(NSUInteger)arg2;
- (id)_instanceVariableDeclarationBlockItemForClassItem:(id)arg1;
- (id)_objCCategoryImplementationClassModelItemForClassNamed:(id)arg1 categoryName:(id)arg2 error:(id *)arg3;
- (id)_objCCategoryInterfaceClassModelItemForClassNamed:(id)arg1 categoryName:(id)arg2 options:(id)arg3 error:(id *)arg4;
- (id)_objCImplementationClassModelItemForClassNamed:(id)arg1 error:(id *)arg2;
- (id)_objCInterfaceClassModelItemForClassNamed:(id)arg1 error:(id *)arg2;
- (id)_classModelItemForClassNamed:(id)arg1 withConditionBlock:(void(^)(void))arg2;
- (id)errorForNotFindingClassItemForClassNamed:(id)arg1 humanReadableClassItemType:(id)arg2;
- (id)supportedSourceCodeLanguagesForSourceCodeGeneration;
- (long long)defaultPropertyAccessControl;
- (id)emptyPrivateCopy;
- (id)privateCopy;
- (id)diffDataSource;
- (id)textViewWillReturnPrintJobTitle:(id)arg1;
- (id)printOperationWithSettings:(id)arg1 error:(id *)arg2;
- (void)sourceLanguageServiceAvailabilityNotification:(BOOL)arg1 message:(id)arg2;
- (BOOL)textStorageShouldAllowEditing:(id)arg1;
- (void)textStorageDidUpdateSourceLandmarks:(id)arg1;
- (void)textStorageDidProcessEditing:(id)arg1;
- (void)updateChangeCount:(NSUInteger)arg1;
- (BOOL)replaceTextWithContentsOfURL:(id)arg1 error:(id *)arg2;
- (BOOL)replaceFindResults:(id)arg1 inSelection:(NSRange)arg2 withString:(id)arg3 withError:(id *)arg4;
- (BOOL)replaceFindResults:(id)arg1 withString:(id)arg2 withError:(id *)arg3;
- (BOOL)replaceFindResults:(id)arg1 withString:(id)arg2 inSelection:(NSRange)arg3 withError:(id *)arg4;
- (id)findStringMatchingDescriptor:(id)arg1 backwards:(BOOL)arg2 from:(id)arg3 to:(id)arg4;
- (id)documentLocationFromCharacterRange:(NSRange)arg1;
- (NSRange)characterRangeFromDocumentLocation:(id)arg1;
- (id)updatedLocationFromLocation:(id)arg1 toTimestamp:(double)arg2;
- (id)indexCompatibleLocationFromLocation:(id)arg1;
- (id)editorCompatibleLocationFromLocation:(id)arg1;
- (void)prefetchNodeTypesExtraLines:(NSUInteger)arg1 upDirection:(BOOL)arg2 withContext:(id)arg3;
- (void)initialPrefetchNodeTypesForLineRange:(NSRange)arg1 withContext:(id)arg2;
- (void)_prefetchNodeTypesForLineRange:(NSRange)arg1 withContext:(id)arg2;
- (long long)nodeTypeForItem:(id)arg1 withContext:(id)arg2;
- (void)_adjustNodeTypeForIdentifierItem:(id)arg1 withContext:(id)arg2;
- (void)editorDocumentWillClose;
- (id)dataOfType:(id)arg1 error:(id *)arg2;
- (BOOL)writeToURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (BOOL)readFromData:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (void)_configureDocumentReadFromURL:(id)arg1 orData:(id)arg2 ofType:(id)arg3 usedEncoding:(NSUInteger)arg4 preferredLineEndings:(NSUInteger)arg5 readOutAttributes:(id)arg6;
- (id)_readOptionsDictionaryForURL:(id)arg1 preferredEncoding:(NSUInteger)arg2 inOutData:(id *)arg3;
- (NSUInteger)_lineEndingUsedInString:(id)arg1;
- (BOOL)canSaveAs;
- (BOOL)canSave;
@property(readonly) DVTPerformanceMetric *openingPerformanceMetric;
- (id)editedContents;
@property(readonly, copy) NSString *description;
- (id)displayName;
@property(readonly) NSArray *knownFileReferences;
- (NSRange)lineRangeOfSourceLandmark:(id)arg1;
- (id)sourceLandmarkItemAtLineNumber:(NSUInteger)arg1;
- (id)sourceLandmarkItemAtCharacterIndex:(NSUInteger)arg1;
@property(readonly) NSArray *ideTopLevelStructureObjects;
- (void)invalidateAndDisableDiagnosticController;
- (void)invalidateDiagnosticController;
@property(retain) IDEDiagnosticController *diagnosticController; // @synthesize diagnosticController=_diagnosticController;
- (id)printInfo;
- (void)setTextEncoding:(NSUInteger)arg1 convertContents:(BOOL)arg2;
@property(readonly, nonatomic) NSDictionary *sourceLanguageServiceContext;
@property(readonly) DVTFileDataType *fileDataType;
- (void)setSdefSupport_text:(id)arg1;
- (id)sdefSupport_text;
- (void)setSdefSupport_selection:(id)arg1;
- (id)sdefSupport_selection;
- (void)setSdefSupport_selectedParagraphRange:(id)arg1;
- (id)sdefSupport_selectedParagraphRange;
- (void)setSdefSupport_selectedCharacterRange:(id)arg1;
- (id)sdefSupport_selectedCharacterRange;
- (void)setSdefSupport_notifiesWhenClosing:(BOOL)arg1;
- (BOOL)sdefSupport_notifiesWhenClosing;
- (void)setSdefSupport_contents:(id)arg1;
- (id)sdefSupport_contents;
- (void)setSdefSupport_editorSettings:(id)arg1;
- (id)sdefSupport_editorSettings;
- (id)objectSpecifier;

@property(readonly) NSURL *fileURL;
@property NSUInteger supportedMatchingOptions;

@end

